In [2]:
import pandas as pd
df = pd.read_csv("data.csv")
df

,emp_id,name,age,department,designation,salary,experience,city
0,101,Amit Sharma,28,IT,Software Engineer,55000.0,4,Bangalore
1,102,Riya Verma,32,HR,HR Manager,60000.0,8,Delhi
2,103,Rahul Mehta,26,IT,Backend Developer,NaN,3,Pune
3,104,Sneha Iyer,35,Finance,Accountant,65000.0,10,Chennai
4,105,Arjun Singh,29,Sales,Sales Executive,45000.0,5,Mumbai
5,106,Neha Gupta,31,IT,Frontend Developer,52000.0,6,Bangalore
6,107,Vikram Rao,38,Operations,Operations Manager,72000.0,14,Hyderabad
7,108,Pooja Nair,27,HR,HR Executive,42000.0,2,Kochi

In [4]:
df.isnull().sum()

emp_id         0
name           0
age            0
department     0
designation    0
salary         1
experience     0
city           0
dtype: int64

In [5]:
df.describe()

          emp_id        age        salary  experience
count    8.00000   8.000000      7.000000        8.00
mean   104.50000  30.750000  55857.142857        6.50
std      2.44949   4.131759  10699.354676        4.00
min    101.00000  26.000000  42000.000000        2.00
25%    102.75000  27.750000  48500.000000        3.75
50%    104.50000  30.000000  55000.000000        5.50
75%    106.25000  32.750000  62500.000000        8.50
max    108.00000  38.000000  72000.000000       14.00

In [6]:
df[df["salary"].isna()]

,emp_id,name,age,department,designation,salary,experience,city
2,103,Rahul Mehta,26,IT,Backend Developer,NaN,3,Pune

In [8]:
df["salary"].mean()

np.float64(55857.142857142855)

In [9]:
df.fillna(df["salary"].mean(), inplace = True)

In [10]:
df

,emp_id,name,age,department,designation,salary,experience,city
0,101,Amit Sharma,28,IT,Software Engineer,55000.000000,4,Bangalore
1,102,Riya Verma,32,HR,HR Manager,60000.000000,8,Delhi
2,103,Rahul Mehta,26,IT,Backend Developer,55857.142857,3,Pune
3,104,Sneha Iyer,35,Finance,Accountant,65000.000000,10,Chennai
4,105,Arjun Singh,29,Sales,Sales Executive,45000.000000,5,Mumbai
5,106,Neha Gupta,31,IT,Frontend Developer,52000.000000,6,Bangalore
6,107,Vikram Rao,38,Operations,Operations Manager,72000.000000,14,Hyderabad
7,108,Pooja Nair,27,HR,HR Executive,42000.000000,2,Kochi

In [11]:
df.to_csv("data.csv", index = False)

In [14]:
df[["salary","designation"]] ## display multiple columns

         salary         designation
0  55000.000000   Software Engineer
1  60000.000000          HR Manager
2  55857.142857   Backend Developer
3  65000.000000          Accountant
4  45000.000000     Sales Executive
5  52000.000000  Frontend Developer
6  72000.000000  Operations Manager
7  42000.000000        HR Executive

In [15]:
df[df["salary"]>50000]  # display employees withdrawing more than 500000

,emp_id,name,age,department,designation,salary,experience,city
0,101,Amit Sharma,28,IT,Software Engineer,55000.000000,4,Bangalore
1,102,Riya Verma,32,HR,HR Manager,60000.000000,8,Delhi
2,103,Rahul Mehta,26,IT,Backend Developer,55857.142857,3,Pune
3,104,Sneha Iyer,35,Finance,Accountant,65000.000000,10,Chennai
5,106,Neha Gupta,31,IT,Frontend Developer,52000.000000,6,Bangalore
6,107,Vikram Rao,38,Operations,Operations Manager,72000.000000,14,Hyderabad

In [16]:
df[(df["salary"]>50000) & (df["department"]=="IT")]# display employees withdrawing more than 500000 and department is IT

,emp_id,name,age,department,designation,salary,experience,city
0,101,Amit Sharma,28,IT,Software Engineer,55000.000000,4,Bangalore
2,103,Rahul Mehta,26,IT,Backend Developer,55857.142857,3,Pune
5,106,Neha Gupta,31,IT,Frontend Developer,52000.000000,6,Bangalore

In [17]:
df[df["salary"]==df["salary"].max()] #printing employee details withdrwaing maximum salary

,emp_id,name,age,department,designation,salary,experience,city
6,107,Vikram Rao,38,Operations,Operations Manager,72000.0,14,Hyderabad

In [20]:
df[df["salary"].isnull()].sum() # displays the rows where the salary is null

emp_id           0
name             0
age              0
department       0
designation      0
salary         0.0
experience       0
city             0
dtype: object

In [22]:
df["bonus"] = 50000
df = df.drop(columns="bonus")
df["new_salary"] = df["salary"]
df.loc[df['department']== 'HR', "new_salary"]*=1.1
df["department"]= df["department"].replace("Operations", 5)

In [23]:
df

,emp_id,name,age,department,designation,salary,experience,city,new_salary
0,101,Amit Sharma,28,IT,Software Engineer,55000.000000,4,Bangalore,55000.000000
1,102,Riya Verma,32,HR,HR Manager,60000.000000,8,Delhi,66000.000000
2,103,Rahul Mehta,26,IT,Backend Developer,55857.142857,3,Pune,55857.142857
3,104,Sneha Iyer,35,Finance,Accountant,65000.000000,10,Chennai,65000.000000
4,105,Arjun Singh,29,Sales,Sales Executive,45000.000000,5,Mumbai,45000.000000
5,106,Neha Gupta,31,IT,Frontend Developer,52000.000000,6,Bangalore,52000.000000
6,107,Vikram Rao,38,5,Operations Manager,72000.000000,14,Hyderabad,72000.000000
7,108,Pooja Nair,27,HR,HR Executive,42000.000000,2,Kochi,46200.000000

In [ ]:
df1 = pd.read_csv("data.csv")